### ISSUE TITLE
Allow clients to request a subset of validity times

### ISSUE THREAD

**Issue by shsms** [frequenz-floss/frequenz-api-weather#60]
### What's needed?

Currently the weather forecast streaming method and the historical forecast method would return all available validity times for every request.  This could be a lot more data than what's actually necessary when there's high resolution data or longer term predictions.

To avoid this, the methods should accept an optional filter for validity times in their requests.

### Proposed solution

A possible implementation could look like this: https://github.com/frequenz-floss/frequenz-api-weather/pull/56/files

**Comment by TalweSingh** [comment]
superseded by #116
