### ISSUE TITLE
MWE for Weather API

### ISSUE THREAD

**Issue by david-natingga-frequenz** [frequenz-floss/frequenz-api-weather#83]
### What's needed?

Weather API should have a minimal working example (MWE) that starts a client and gets some simple data.

**Comment by cwasicki** [comment]
For streaming we can use this: https://github.com/cwasicki/frequenz-api-weather/blob/wc/wc/test.py

**Comment by david-natingga-frequenz** [comment]
MWE for both historical and live data have been provided in https://github.com/frequenz-floss/frequenz-api-weather/pull/85.
