### ISSUE TITLE
Create a configuration for the client

### ISSUE THREAD

**Issue by david-natingga-frequenz** [frequenz-floss/frequenz-api-weather#96]
### What's needed?

The client should have a TOML configuration that should include the following fields:
- `PAGE_SIZE = 20`

**Comment by shsms** [comment]
No, that would make it hard for users of the client.  Only apps should have config files and the clients should define all configurable parameters as arguments that apps can override.

**Comment by david-natingga-frequenz** [comment]
> No, that would make it hard for users of the client. Only apps should have config files and the clients should define all configurable parameters as arguments that apps can override.

@shsms Then would about @cwasicki 's comment here?: https://github.com/frequenz-floss/frequenz-api-weather/pull/89#discussion_r1556216728

**Comment by david-natingga-frequenz** [comment]
We do not need this anymore.
